version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: action
      POSTGRES_DB: pigeonSecurity
    networks:
      - my_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-container
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-container
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: action
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - my_network
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres
    command: start-dev

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app2-container
    networks:
      - my_network
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/pigeonSecurity
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: action
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak-container:8080/realms/pigeonSecurity
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: spring-boot-app
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: HC8CAdJXicjYIHBXBTOUvTifFGqnqoXM
    volumes:
      - keystore_volume:/app
    depends_on:
      - postgres
      - keycloak

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-container
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    networks:
      - my_network
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - spring-app


volumes:
  postgres_data:
  keycloak_data:
  keystore_volume:
  jenkins_home:


networks:
  my_network:
    driver: bridge
